package com.stockroompro.loaders;

/**
 * Created by bagach.alexandr on 25.03.15.
 */
public interface LoadersId {

    int DB_CATEGORIES_LOADER_ID = 1;
    int NETWORK_CATEGORIES_LOADER_ID = 2;
    int DB_SUB_CATEGORIES_LOADER_ID = 3;
    int NETWORK_SUB_CATEGORIES_LOADER_ID = 4;
    int NETWORK_AUTHORIZATION_LOADER_ID = 5;
    int NETWORK_REGISTRATION_LOADER_ID = 6;
    int NETWORK_RESTORE_PASSWORD_LOADER_ID = 7;
    int NETWORK_SOCIAL_AUTHORIZATION_LOADER_ID = 8;
    int NETWORK_SOCIAL_REGISTRATION_LOADER_ID = 9;
    int NETWORK_USER_DATA_LOADER_ID = 10;
    int NETWORK_DELETE_PROFILE_LOADER_ID = 11;
    int NETWORK_SOCIAL_SYNCHRONIZATION_LOADER_ID = 12;
    int NETWORK_CHANGE_PASSWORD_LOADER_ID = 13;
    int NETWORK_EDIT_PROFILE_LOADER_ID = 14;

    int DB_ADVERTISEMENT_LOADER_ID = 15;
    int DB_ADVERTISEMENT_LOADER_PAGINATION_ID = 155;
    int NETWORK_ADVERTISEMENT_LOADER_ID = 16;
    int NETWORK_MESSAGES_BY_USERS_LOADER_ID = 17;
    int DB_MESSAGE_BY_USER_LOADER_ID = 18;
    int NETWORK_MESSAGES_BY_ADVERT_LOADER_ID = 19;
    int DB_MESSAGE_BY_ADVERT_LOADER_ID = 20;
    int DB_PHOTO_LOADER_ID = 21;
    int DB_CHAT_MESSAGE_LOADER_ID = 22;
    int DB_ADVERTISEMENT_DETAILS_LOADER_ID = 23;
    int NETWORK_DELETE_PROFILE_PHOTO_ID = 24;
    int NETWORK_EDIT_PROFILE_PHOTO_ID = 25;


    int NETWORK_FILTERS_LOADER_ID = 26;
    int NETWORK_ADVERT_USER_DATA_LOADER_ID = 27;
    int DB_ADVERT_USER_DATA_LOADER_ID = 28;
    int DB_ADVERT_FILTERS_LOADER_ID = 29;
    int NETWORK_ADVERT_FILTERS_LOADER_ID = 30;
    int NETWORK_ADD_ADVERTISEMENT_LOADER_ID = 31;
    int NETWORK_RATING_SETTER_LOADER_ID = 32;
    int NETWORK_USER_ADS_LOADER_ID = 33;
    int DB_USER_ADS_LOADER_ID = 34;
    int NETWORK_SEND_MESSAGE_LOADER_ID = 35;
    int DB_MESSAGES_SEARCH_LOADER_ID = 36;
    int DB_INSERT_CHAT_MESSAGE_TO_DB_LOADER_ID = 37;
    int NETWORK_CHAT_MESSAGE_LOADER_ID = 38;
    int NETWORK_ADVERTISEMENT_DETAILS_LOADER_ID = 39;
    int DB_CATEGORIES_ADD_ADVERT_LOADER_ID = 40;

    int SEARCH_LOADER = 42;
    int FAVOURITES_ONLINE_LOADER = 43;
    int ADD_FAVOURITES_LOADER = 44;
    int FAVOURITES_DB_LOADER = 45;
    int COMMENTS_LOADER = 46;
    int ADD_COMMENT_LOADER = 47;
    int DB_COMMENTS_LOADER = 48;

    int NETWORK_COUNTRY_LOADER_ID = 49;
    int NETWORK_REGION_LOADER_ID = 50;
    int NETWORK_CITY_LOADER_ID = 51;
    int ADD_ADVERT_PHOTOS_LOADER_ID = 52;
    int ADVERT_PHOTOS_DB_LOADER = 53;
    int COMMENTS_COUNT_LOADER_ID = 54;
    int SUBSCRIBE_GCM_LOADER = 55;
    int UNSUBSCRIBE_GCM_LOADER = 56;
    int DB_GCM_LOADER = 57;
    int NETWORK_GCM_LOADER = 58;
    int NETWORK_EDIT_ADVERTISEMENT_LOADER_ID = 59;
    int DB_FILTERS_BY_CATEGORY = 60;
    int DB_FILTER_PRICE_RANGES = 61;
    int NETWORK_DELETE_ADVERT = 62;
    int NETWORK_ADERTS_LOADER_BY_FILTERS_ID = 63;
    int NETWORK_ADERTS_LOADER_BY_PAGINATION_ID = 633;
    int EXTEND_ADVERT_LOADER_ID = 64;

    int DB_NOTIFICATION_IMPORTANT_LOADER = 65;
    int DB_NOTIFICATION_RATES_LOADER = 66;
    int DB_NOTIFICATION_COMMUNICTION_LOADER = 67;
    int DB_NOTIFICATION_LOADER = 68;
    int ADD_LIKE_TO_COMMENT = 69;
    int DB_NOTIFICATION_STATUS_LOADER = 70;
    int ADVERT_DETAIL_FROM_COMMENTS_LOADER_ID = 71;

    int LAUNCHER_NETWORK_COUNTRY_LOADER_ID = 72;
    int LAUNCHER_NETWORK_REGION_LOADER_ID = 73;
    int LAUNCHER_NETWORK_CITY_LOADER_ID = 74;

    int EDIT_ADVERT_FILTERS = 75;
}
